{% set name = "phasexmlcreator" %}
{% set version = "3.0.1" %}
{% set sha256 = "0e1bcb87057ee3e61fa9be7b26af25d0dfc325617fb0628db43cc2627f632b7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.developers.cam.ac.uk/ch/hunter/ssiptools/ssimpleapps/phasexmlcreator/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
    - pandas
    - xmlvalidator

test:
  imports:
    - phasexmlcreator
  requires:
    - pytest
  commands:
    - pytest --pyargs phasexmlcreator

about:
  home: https://gitlab.developers.cam.ac.uk/ch/hunter/ssiptools/ssimpleapps/phasexmlcreator
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: COPYING
  summary: Module for converting SSIP XML descriptions to Phase XML formats.
  description: |
    Module for the conversion of SSIP XML to phase, solvent and solute XML.
    Part of the SSIPTools suite of tools.
  doc_url: https://gitlab.developers.cam.ac.uk/ch/hunter/ssiptools/ssimpleapps/phasexmlcreator
  dev_url: https://gitlab.developers.cam.ac.uk/ch/hunter/ssiptools/ssimpleapps/phasexmlcreator

extra:
  recipe-maintainers:
    - mjw99
    - mdd31
